# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75aabdc5c5c57e371b99e0a63fc880a00d2295125d51d1a0400848cca02dbebe8a11add5cb443236ed503c786868f0a18781a6940acb6eb38209aa46148bb946

test:
  secret_key_base: 2447a210a2827708227dd9dc359ea3a80791e566aa480d1d8668dabc748c4130fd89e7252b4a655b724e6a076deb767ba7c4bb31262dc845a6746cd0ca0f42c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
